name: brdnet
channels:
    - conda-forge
    - r
    - bioconda
dependencies:
    - r::r=3.5.1
    - r::r-xml2=1.2.0
    - conda-forge::python=3.7
    - conda-forge::pandas=0.24.2
    - conda-forge::rpy2=2.9.4
    - conda-forge::requests=2.22.0
    - conda-forge::plotnine=0.5.1
    - conda-forge::r-dplyr=0.8.3
    - conda-forge::ipykernel=5.1.1
    - conda-forge::jupyter=1.0.0
    - bioconda::bioconductor-recount=1.8.1
